name: CI to Docker Hub

on:
  release:
    types: [published]

jobs:
  docker-hub-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Docker build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
          image_name: ${{ secrets.DOCKER_HUB_USERNAME }}/next-cache
          image_tag: ${{ steps.get_version.outputs.SOURCE_TAG }},latest
          context: .
          dockerfile: Dockerfile
